version: '3.8'

services:

  backend-note:
    container_name: backend-note
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db-note
    env_file:
      - .properties


  db-note:
    image: bitnami/postgresql:14
    container_name: db-note
    env_file:
      - .properties
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: