apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: db-note
spec:
  selector:
    app: db-note
  ports:
    - port: 5440
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-note
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-note
  template:
    metadata:
      labels:
        app: db-note
    spec:
      containers:
        - name: db-note
          image: bitnami/postgresql:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRESQL_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRESQL_DATABASE
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-volume





